 let str = 'In space, no one can hear you code.';
 console.log(str.split());
console.log(str.split('e'));
console.log(str.split(' '));
console.log(str.split(''));
let arr=['B','n','n',5];
console.log(arr.join());
console.log(arr.join('a'));
console.log(arr.join(' '));
console.log(arr.join(''));